#!/bin/bash
LOG=/tmp/sonar.log
ID=$(id -u)

if [ $ID -ne 0 ] ; then
   echo " you are the root user, you dont have permissions to run this "
   exit 1
else
    echo " you are running script file successfu;lly using root user"
fi

echo " Installing SonarQube Dependencies "
yum install wget java unzip -y &>>$LOG

if [ $? -ne 0 ] ; then
   echo " Installing SonarQube Dependencies ... Failed "
   exit 1
else
    echo " Installing SonarQube Dependencies ... Success"
fi	

echo " Downloading Mysql Package "
wget http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm -O /tmp/mysql-community-release-el7-5.noarch.rpm &>>$LOG
#-O /tmp/mysql-community-release-el7-5.noarch.rpm &>>$LOG

if [ $? -ne 0 ] ; then
   echo " Downloading Mysql Package ... Failed "
   exit 1
else
    echo " Downloading Mysql Package ... Success"
fi	

echo " Installing Mysql rpm Package "
#cd /tmp/
rpm -ivh cd /tmp/mysql-community-release-el7-5.noarch.rpm  &>>$LOG
yum install  mysql-community-server -y 

if [ $? -ne 0 ] ; then
   echo " Installing Mysql rpm Package ... Failed "
   exit 1
else
    echo " Installing Mysql rpm Package ... Success"
fi	

echo " Starting Myqsl "
systemctl start mysql 

if [ $? -ne 0 ] ; then
   echo " Starting Myqsl ... Failed "
   exit 1
else
    echo " Starting Myqsl ... Success"
fi	

echo "SonarQube Database Update"
echo "CREATE DATABASE sonarqube_db;
CREATE USER 'sonarqube_user'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON sonarqube_db.* TO 'sonarqube_user'@'localhost' IDENTIFIED BY 'password';
FLUSH PRIVILEGES;" > /tmp/sonar.sql

