#!/bin/bash
LOG=/tmp/sonar.log
ID=$(id -u)

if [ $ID -ne 0 ] ; then
   echo " you are the root user, you dont have permissions to run this "
   exit 1
else
    echo " you are running script file successfu;lly using root user"
fi

echo " Installing SonarQube Dependencies "
yum install wget java1.8.0-openjdk  -y &>>$LOG

if [ $? -ne 0 ] ; then
   echo " Installing SonarQube Dependencies ... Failed "
   exit 1
else
    echo " Installing SonarQube Dependencies ... Success"
fi	

echo " Downloading Mysql Package "
wget http://repo.mysql.com/mysql-community-release-el7-5.noarch.rpm -O /tmp/mysql-community-release-el7-5.noarch.rpm &>>$LOG
#-O /tmp/mysql-community-release-el7-5.noarch.rpm &>>$LOG

if [ $? -ne 0 ] ; then
   echo " Downloading Mysql Package ... Failed "
   exit 1
else
    echo " Downloading Mysql Package ... Success"
fi	

echo " Installing Mysql rpm Package "
cd /tmp/
rpm -ivh mysql-community-release-el7-5.noarch.rpm  &>>$LOG
yum install  mysql-community-server -y  &>>$LOG

if [ $? -ne 0 ] ; then
   echo " Installing Mysql rpm Package ... Failed "
   exit 1
else
    echo " Installing Mysql rpm Package ... Success"
fi	

echo " Starting Myqsl "
systemctl start mysql 

if [ $? -ne 0 ] ; then
   echo " Starting Myqsl ... Failed "
   exit 1
else
    echo " Starting Myqsl ... Success"
fi	

echo "SonarQube Database Update"
echo "CREATE DATABASE sonarqube_db;
CREATE USER 'sonarqube_user'@'localhost' IDENTIFIED BY 'password';
GRANT ALL PRIVILEGES ON sonarqube_db.* TO 'sonarqube_user'@'localhost' IDENTIFIED BY 'password';
FLUSH PRIVILEGES;" > /tmp/sonar.sql

mysql </tmp/sonar.sql

#if [ -f /tmp/sonar.sql ] ; then 
#    echo " SonarQube Database Update ..!"
#else
#	echo "SonarQube Database Update"
#	echo "CREATE DATABASE sonarqube_db;
#	CREATE USER 'sonarqube_user'@'localhost' IDENTIFIED BY 'password';
#	GRANT ALL PRIVILEGES ON sonarqube_db.* TO 'sonarqube_user'@'localhost' IDENTIFIED BY 'password';
#	FLUSH PRIVILEGES;" > /tmp/sonar.sql
#	mysql </tmp/sonar.sql
#fi



if [ $? -ne 0 ] ; then
   echo " Database update ... Failed "
else
   echo "Database update ... Success"
fi	

echo " Creating sonarqube user account "
useradd sonarqube
if [ $? -ne 0 ] ; then
   echo " Creating sonarqube user account ... Failed "
else
   echo " Creating sonarqube user account ... Success"
fi

echo "Downloading sonarqube"
wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-6.7.6.zip  -O /tmp/sonarqube-6.7.6.zip &>>$LOG
if [ $? -ne 0 ] ; then
   echo " Downloading sonarqube ... Failed "
else
   echo " Downloading sonarqube ... Success"
fi

echo " Extracting Soanrqube package"
unzip -o /tmp/sonarqube-6.7.6.zip  &>>$LOG
mv sonarqube-6.7.6 /opt/sonarqube
chown sonarqube. /opt/sonarqube -R
if [ $? -ne 0 ] ; then
   echo " Extracting Soanrqube package ... Failed "
else
   echo " Extracting Soanrqube package ... Success"
fi

echo "Soanrqube DB configuration Update"
echo 'sonar.jdbc.username=sonarqube_user
sonar.jdbc.password=password
sonar.jdbc.url=jdbc:mysql://localhost:3306/sonarqube_db?useUnicode=true&amp;characterEncoding=utf8&amp;rewriteBatchedStatements=true&amp;useConfigs=maxPerformance' > /opt/sonarqube/conf/sonar.properties

#or
#if [ -d /opt/sonarqube ] ; then
#        echo " Sonarqube is installation is .. Done "
#else  
#   wget https://binaries.sonarsource.com/Distribution/sonarqube/sonarqube-6.7.6.zip  -O /tmp/sonarqube-6.7.6.zip &>>$LOG
#   echo " Extracting Soanrqube package"
#  unzip -o /tmp/sonarqube-6.7.6.zip  &>>$LOG	
#	mv sonarqube-6.7.6 /opt/sonarqube
#	chown sonarqube. /opt/sonarqube -R
#	echo 'sonar.jdbc.username=sonarqube_user
#    sonar.jdbc.password=password
#   sonar.jdbc.url=jdbc:mysql://localhost:3306/sonarqube_db?useUnicode=true&amp;characterEncoding=utf8&amp;rewriteBatchedStatements=true&amp;useConfigs=maxPerformance' > /opt/sonarqube/conf/sonar.properties
#fi

echo " Updating Sonarqude sonar.sh file "
sed -i 's/#RUN_AS_USER=/RUN_AS_USER=sonarqube/g' /opt/sonarqube/bin/linux-x86-64/sonar.sh

if [ $? -ne 0 ] ; then
   echo " Updating Sonarqude sonar.sh file ... Failed "
else
   echo " Updating Sonarqude sonar.sh file ... Success"
fi

sh /opt/sonarqube/bin/linux-x86-64/sonar.sh start 
